# Generated by Django 5.1.7 on 2025-03-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voltaje_fase_1', models.FloatField()),
                ('voltaje_fase_2', models.FloatField()),
                ('voltaje_fase_3', models.FloatField()),
                ('corriente_fase_1', models.FloatField()),
                ('corriente_fase_2', models.FloatField()),
                ('corriente_fase_3', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='ModbusData',
        ),
    ]
