# Generated by Django 5.1.7 on 2025-03-20 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0002_registroenergia_delete_modbusdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroenergia',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
