# Generated by Django 5.1.7 on 2025-03-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0003_alter_registroenergia_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroenergia',
            name='energia_activa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroenergia',
            name='energia_reactiva',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroenergia',
            name='potencia_activa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroenergia',
            name='potencia_aparente',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroenergia',
            name='potencia_reactiva',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroenergia',
            name='corriente_fase_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroenergia',
            name='corriente_fase_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroenergia',
            name='corriente_fase_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroenergia',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registroenergia',
            name='voltaje_fase_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroenergia',
            name='voltaje_fase_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroenergia',
            name='voltaje_fase_3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
